name: "Destroy Infrastructure"
description: "This workflow destroys the infrastructure provisioned by Terraform. It is intended to be run manually when you want to tear down the environment."

on:
  workflow_dispatch:

env:
  # verbosity setting for Terraform logs
  TF_LOG: INFO
  # Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_TOKEN_app_terraform_io: "${{ secrets.TF_API_TOKEN }}"

jobs:
  terraform:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the terraform directory.
        working-directory: ./infrastructure/terraform

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.33.0"

      - name: Install Helm
        uses: azure/setup-helm@v4.3.0

      - name: Update kubeconfig file
        run: |
          aws eks update-kubeconfig --region us-east-1 --name eks-cluster --kubeconfig  ${{ github.workspace }}/kubeconfig

      - name: Uninstall the Helm release
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: |
          helm uninstall nodejs-ms

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve -input=false
